
import './globals.css'
import Header from "@/components/header/header"
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Esselife',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='dark:bg-slate-400'>
        <Toaster
          position="bottom-right"
          reverseOrder={false} />
        <div className="sticky top-0 z-50"><Header /></div>
        <main>{children}</main>
      </body>
    </html>
  )
}
